### Global & dlt components
[runtime]
log_level="WARNING"

### Destinations

# nothing to configure...

### Sources

## chess

[sources.chess.extract]
max_parallel_items = 5
workers = 2  # limit the parallel execution

# the section below defines config values for "chess_dlt_config_example" source in chess/__init__.py
[sources.chess]
config_int=123

# Google Analytics config
[sources.google_analytics.google_analytics]
queries = [{resource_name = "sample_analytics_data1", dimensions = ["browser", "city", "dateHour" ,"date"], metrics = ["totalUsers", "transactions"]},
            {resource_name = "sample_analytics_data2", dimensions = ["browser", "city"], metrics = ["totalUsers", "transactions"]}]
scope = "https://www.googleapis.com/auth/analytics.readonly"
redirect_uri = "https://localhost"
property_id = 293833391
rows_per_page = 1000
start_date = "2000-01-01"

# Matomo config
[sources.matomo.matomo]
queries = [{resource_name = "sample_analytics_data1", methods = ["VisitsSummary.get", "API.getReportMetadata"], date = "previous100", period = "day", site_id = 2, extra_params = {}},
    {resource_name = "sample_analytics_data2", methods = ["VisitsSummary.get", "API.getReportMetadata"], date = "2022-03-02", period = "month", site_id = 2}]
filter_limit = 3

## sql_database
[sources.sql_database.data_writer]
buffer_max_items=5000


[sources.google_sheets.google_spreadsheet]
range_names = []
spreadsheet_identifier = "https://docs.google.com/spreadsheets/d/1HhWHjqouQnnCIZAFa2rL6vT91YRN8aIhts22SUUR580/edit#gid=0"

