### Global & dlt components
[runtime]
log_level="WARNING"

### Destinations

# nothing to configure...

### Sources

## chess

[sources.chess.extract]
max_parallel_items = 5
workers = 2  # limit the parallel execution

# the section below defines config values for "chess_dlt_config_example" source in chess/__init__.py
[sources.chess]
config_int=123

[sources.shopify]
api_version="2023-01"
rate_limit=2
initial_days_back=30

## sql_database

[sources.sql_database.data_writer]
buffer_max_items=5000